# Generated by Django 6.0.3 on 2026-04-15 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_search_alert_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alerte'},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alert_radius_km',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alerts_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('new_listing', 'Nouvelle annonce'), ('recommendation', 'Recommandation'), ('proximity', 'À proximité'), ('admin_message', 'Message administrateur')], default='new_listing', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('admin_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
